// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKTZgqyhPahSq_OT2mSQV8IquQxHV8hf8',
    appId: '1:968154377505:web:fbaace16da026454206260',
    messagingSenderId: '968154377505',
    projectId: 'mynoticfication',
    authDomain: 'mynoticfication.firebaseapp.com',
    storageBucket: 'mynoticfication.firebasestorage.app',
    measurementId: 'G-XP8F1571JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA194PfZU-mRTiOSm3lNLhFoLz392gJB2c',
    appId: '1:968154377505:android:6cde5d59cd53442f206260',
    messagingSenderId: '968154377505',
    projectId: 'mynoticfication',
    storageBucket: 'mynoticfication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrYxPVIxhlNDCLG8l6B8K70u5QFTipImA',
    appId: '1:968154377505:ios:32bbd6e204c1532f206260',
    messagingSenderId: '968154377505',
    projectId: 'mynoticfication',
    storageBucket: 'mynoticfication.firebasestorage.app',
    iosBundleId: 'com.example.adminMenuExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrYxPVIxhlNDCLG8l6B8K70u5QFTipImA',
    appId: '1:968154377505:ios:32bbd6e204c1532f206260',
    messagingSenderId: '968154377505',
    projectId: 'mynoticfication',
    storageBucket: 'mynoticfication.firebasestorage.app',
    iosBundleId: 'com.example.adminMenuExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKTZgqyhPahSq_OT2mSQV8IquQxHV8hf8',
    appId: '1:968154377505:web:004aa7fdf66e43e9206260',
    messagingSenderId: '968154377505',
    projectId: 'mynoticfication',
    authDomain: 'mynoticfication.firebaseapp.com',
    storageBucket: 'mynoticfication.firebasestorage.app',
    measurementId: 'G-3EDD36EBSZ',
  );
}
